### ISSUE TITLE
datatype rdf:XMLLiteral not properly handled

### ISSUE THREAD

**Issue by tistre** [rdfa/rdfa-website#16]
According to http://www.w3.org/TR/2012/REC-rdfa-core-20120607/#T-xml-literals , datatype="rdf:XMLLiteral" should result in the property value containing the full HTML markup.

This currently doesn’t seem to work; shows just the plain text “RDFa 1.1 Primer” without the “b” markup:

``` xml
<span vocab="http://schema.org/" typeof="Document">
  <span property="dc:title" datatype="rdf:XMLLiteral">RDFa <b>1.1</b> Primer</span>
</span>
```

**Comment by gkellogg** [comment]
This issue was moved to rdfa/rdfa.github.io#7
