### ISSUE TITLE
Make table headers sticky in EARL reports

### ISSUE THREAD

**Issue by scor** [rdfa/rdfa-website#19]
This would help digest the new total percentage of PASS for example, and in general while scrolling the long tables.

A few jQuery libraries are available, though I haven't tested any:
- https://github.com/jmosbech/StickyTableHeaders
- http://css-tricks.com/persistent-headers/
- https://github.com/markmalek/Fixed-Header-Table
- https://github.com/benjaminleouzon/tablefixedheader

**Comment by gkellogg** [comment]
This issue was moved to rdfa/rdfa.github.io#8
