### ISSUE TITLE
Graph visualization is re-drawn on change, not updated

### ISSUE THREAD

**Issue by msporny** [rdfa/rdfa-website#2]
D3.js, which is used for the graph visualization, allows graphs to be morphed and updated based on changes to the underlying data. Currently, the visualization is destroyed completely and then re-created, which is wasteful and not very slick looking. Update the graph visualization so that it smoothly adds and remove nodes, perhaps showing which items were added and removed.

**Comment by Haroenv** [comment]
+1

**Comment by gkellogg** [comment]
This issue was moved to rdfa/rdfa.github.io#3
