### ISSUE TITLE
Highlight corresponding content when interacting with graph visualization

### ISSUE THREAD

**Issue by niklasl** [rdfa/rdfa-website#3]
It would be nice if the origin elements are highlighted (or flashed, e.g. using a CSS3 transition) when visualized nodes are hovered or clicked on.

The `origin` property of a triple (or e.g. `document.getElementsBySubject`) may provide hooks for this (although `origin` didn't seem to be exposed by the things returned by DocumentData..).

**Comment by gkellogg** [comment]
This issue was moved to rdfa/rdfa.github.io#4
