### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded error in Play

### ISSUE THREAD

**Issue by scor** [rdfa/rdfa-website#46]
This is happening in Chrome and FF. When trying the markup below, I get the error "Uncaught RangeError: Maximum call stack size exceeded"

To reproduce, try these at http://rdfa.info/play/:
```
<body vocab="http://schema.org/" prefix="cco: http://purl.org/ontology/cco/core# foaf: http://xmlns.com/foaf/0.1/">
<div about="https://wwelves.org/perpetual-tripper" typeof="Person foaf:Person">
  <ul rel="contactPoint">
    <li about="xmpp:perpetual-tripper@wwelves.org" typeof="ContactPoint">
      <a rel="me" href="xmpp:perpetual-tripper@wwelves.org"><span property="name">jabber (xmpp)</span></a>
    </li>
  </ul>
</div>
</body>
```
It comes from @href. If you empty the href attribute, the error goes away. I thought it was due to the xmpp:, but it breaks also with regular urls.

```
<body vocab="http://schema.org/" prefix="cco: http://purl.org/ontology/cco/core# foaf: http://xmlns.com/foaf/0.1/">
<div about="https://wwelves.org/perpetual-tripper" typeof="Person foaf:Person">
  <ul rel="contactPoint">
    <li about="https://github.com/elf-pavlik" typeof="ContactPoint">
      <a rel="me" href="https://github.com/elf-pavlik"><span property="name">Github</span></a>
    </li>
  </ul>
</div>
</body>
```

Pinging @alexmilowski just in case, not sure if the problem is in the Play js or in Green Turtle.

**Comment by vicvicvic** [comment]
This happens with the simplest mark-up where you try to set a link to the same URL as the subject URL, e.g.

    <div vocab="http://schema.org/" about="http://example.com">
      <a href="http://example.com" property="url">Name</a>
    </div>

Some kind of infinite recursion is obviously happening here.
