### ISSUE TITLE
empty tags incorrectly handled as opening tags

### ISSUE THREAD

**Issue by richard-verhoeven** [rdfa/rdfa-website#50]
The following HTML code:

``` html
<body vocab="http://schema.org/">
<div typeof="EventVenue">
    <span property="address" typeof="PostalAddress">
          <span property="addressCountry" content="DE"></span>
    </span>
    <span property="geo" typeof="GeoCoordinates">
      <span property="latitude" content="50.944525"/>
      <span property="longitude" content="6.951725"/>
    </span>
  </div>
</body>
```

is interpreted correctly, i.e. `geo` and `address` are both properties of `EventVenue`. With the following equivalent code instead:

``` html
<body vocab="http://schema.org/">
<div typeof="EventVenue">
    <span property="address" typeof="PostalAddress">
          <span property="addressCountry" content="DE"/>
    </span>
    <span property="geo" typeof="GeoCoordinates">
      <span property="latitude" content="50.944525"/>
      <span property="longitude" content="6.951725"/>
    </span>
  </div>
</body>
```

the `geo` property is interpreted as a property of `PostalAddress`, which is wrong. It would appear that the parser works by counting closing html tags without recognizing that empty ones do not need closing ones.

**Comment by halindrome** [comment]
Technically span isn't allowed to use the /> shorthand.  However, the
parser shouldn't know that nor care about it.

On Wed, Nov 18, 2015 at 3:03 AM, richard-verhoeven <notifications@github.com
> wrote:

> The following HTML code:
>
> <body vocab="http://schema.org/">
> <div typeof="EventVenue">
>     <span property="address" typeof="PostalAddress">
>           <span property="addressCountry" content="DE"></span>
>     </span>
>     <span property="geo" typeof="GeoCoordinates">
>       <span property="latitude" content="50.944525"/>
>       <span property="longitude" content="6.951725"/>
>     </span>
>   </div>
> </body>
>
> is interpreted correctly, i.e. geo and address are both properties of
> EventVenue. With the following equivalent code instead:
>
> <body vocab="http://schema.org/">
> <div typeof="EventVenue">
>     <span property="address" typeof="PostalAddress">
>           <span property="addressCountry" content="DE"/>
>     </span>
>     <span property="geo" typeof="GeoCoordinates">
>       <span property="latitude" content="50.944525"/>
>       <span property="longitude" content="6.951725"/>
>     </span>
>   </div>
> </body>
>
> the geo property is interpreted as a property of PostalAddress, which is
> wrong. It would appear that the parser works by counting closing html tags
> without recognizing that empty ones do not need closing ones.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rdfa/rdfa-website/issues/50>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by niklasl** [comment]
I'm afraid it does. The playground is for trying out HTML5 (and SVG), and not strict XML. The parser is the HTML parser of the web browser, following the rules of parsing [HTML(5)](http://www.w3.org/TR/html-markup/syntax.html). That acknowledges the self-closing (XML-)notation on elements defined as void (but as such they don't even need closing). If this behaviour isn't according to [spec](http://www.w3.org/TR/html5/syntax.html#acknowledge-self-closing-flag) for `span` (which I doubt), the bug needs to be reported to Chrome, Firefox and wherever else this happens.

To visualize how the browser nests the resulting elements, add some style to the `span` along with some text (presumably) outside of that, like:

```html
    <span style="text-decoration: underline" property="address" typeof="PostalAddress">
      a<span property="addressCountry" content="DE"/> b
    </span>c
    <span property="geo" typeof="GeoCoordinates">d
```
Notice how every letter is underlined.

The recommended way of embedding "hidden" data is to use `meta` with `@property` ([whose presence qualifies it as a flow element](http://www.w3.org/TR/html-rdfa/#extensions-to-the-html5-syntax)), like:

```html
    <meta property="addressCountry" content="DE"/>
````
That is a void element, and as such the self-closing slash is optional (basically for show).

**Comment by gkellogg** [comment]
This issue was moved to rdfa/rdfa.github.io#12
