### ISSUE TITLE
datatype rdf:HTML not properly handled

### ISSUE THREAD

**Issue by darobin** [rdfa/rdfa-website#52]
This is similar to #16. The following code actually trips over and errors in the console:

``` html
<span vocab="http://schema.org/" typeof="Document">
  <span property="dc:title" datatype="rdf:HTML">RDFa <b>1.1</b> Primer</span>
</span>
```

What's going on is that the value is actually a DOM node. It tries to figure out what to do with it by looking at its `type`; but of course the DOM node doesn't have one. So it tries to escape it as a string, which simply doesn't work.

**Comment by gkellogg** [comment]
This issue was moved to rdfa/rdfa.github.io#13
