### ISSUE TITLE
Website not working: ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by marc1404** [rdfa/rdfa-website#56]
Hi guys,

when I try to visit rdfa.info I see the following error:

```
This page isn’t working
rdfa.info redirected you too many times.
ERR_TOO_MANY_REDIRECTS
```

I've tested on:
- macOS Chrome & Safari
- iOS Chrome & Safari
- Windows Chrome

**Comment by gkellogg** [comment]
Yes, there is some problem on the site, and our plan is to re-deploy onto gh-pages shortly.

Gregg Kellogg

**Comment by BigBlueHat** [comment]
Great work @gkellogg! Looks like it's back up and running.

Guessing we should start discussing other deployment options for the test suite next? 😃 

Thanks again for getting this back online!

**Comment by marc1404** [comment]
Thank you for fixing! I will close this issue as the site is working again :)
