### ISSUE TITLE
Examples don't work anymore

### ISSUE THREAD

**Issue by comfyneet** [rdfa/rdfa-website#57]
Recent updates made the example buttons unclickable: http://rdfa.info/play/

WaybackMachine showed that these link buttons had worked before: https://wayback.archive.org/web/20161007010043/http://rdfa.info:80/play/ (captured Oct-07-2016)

**Comment by gkellogg** [comment]
May be due to updating jQuery version.

Note that the playground, along with the rest of the site, is now at http://github.com/rdfa/rdfa.github.io

**Comment by gkellogg** [comment]
Fixed in https://github.com/rdfa/rdfa.github.io/commit/34decabb8c186d1c0533df3b5eeb15a477a2b49a.
